var calligraphy = [
    {
        id:10001,
        type:"",
        style:"",
        title:"",
        titleCN:"",
        text:"Read wide, and you will wisely write",
        textCN:"",
        img:"",
        horizontal:false,
    
},
    {
        id:10002,
        type:"",
        style:"",
        title:"",
        titleCN:"",
        text:"Flowing clouds, bamboo leaves, inviting moon with plum blossoms",
        textCN:"",
        img:"",
        horizaontal:false,
    
},
    {
        id:10003,
        type:"",
        style:"",
        title:"",
        titleCN:"",
        text:"The mountain goes with the wilderness, and the river flows into the wilderness.",
        textCN:"",
        img:"",
        horizontal:false,
},
    {
        id:10004,
        type:"",
        style:"",
        title:"",
        titileCN:"",
        text:"Zen tea",
        textCN:"",
        img:"",
        horizontal:true,
},
    {
        id:10005,
        type:"",
        style:"",
        title:"",
        titleCN:"",
        text:"I sent my heart to the moon, with the wind until Yelangxi",
        textCN:"",
        img:"",
        horizontal:false,
},
    {
        id:10006,
        type:"",
        style:"",
        title:"",
        titileCN:"",
        text:"Long winds of tens of thousands of miles, blowing through Yumenguan",
        textCN:"",
        img:"",
        horizontal:false,
},
    {
        id:10007,
        type:"",
        style:"",
        title:"",
        titileCN:"",
        text:"Stopping in my sedan chair in the evening, I sit admiring the maple grove",
        textCN:"",
        img:"",
        horizontal:false,
},
    {
        id:10008,
        type:"",
        style:"",
        title:"",
        titileCN:"",
        text:"Before a step to success, you was gone,people in memory of you with tear fulfil their eyes",
        textCN:"",
        img:"",
        horizontal:false,
},
    {
        id:10009,
        type:"",
        style:"",
        title:"",
        titileCN:"",
        text:"Go to the place where there is scarcity of water, sit and watch the clouds rise",
        textCN:"",
        img:"",
        horizontal:false,
},
{
    id:10010,
    type:"",
    style:"",
    title:"",
    titleCN:"",
    text:"Read wide, and you will wisely write",
    textCN:"",
    img:"",
    horizontal:false,

},
{
    id:10011,
    type:"",
    style:"",
    title:"",
    titleCN:"",
    text:"From distance, mountain is richly colorful.At close-up, flowing water does not make a sound.",
    textCN:"",
    img:"",
    horizaontal:false,

},
{
    id:10012,
    type:"",
    style:"",
    title:"",
    titleCN:"",
    text:"The trees are on the pathway while the grass is wet due to the rain at night",
    textCN:"",
    img:"",
    horizontal:false,
},
{
    id:10013,
    type:"",
    style:"",
    title:"",
    titileCN:"",
    text:"The mountain goes with the wilderness, and the river flows into the wilderness. ",
    textCN:"",
    img:"",
    horizontal:true,
},
{
    id:10014,
    type:"",
    style:"",
    title:"",
    titleCN:"",
    text:"From distance, mountain is richly colorful.At close-up, flowing water does not make a sound. ",
    textCN:"",
    img:"",
    horizontal:false,
},
{
    id:10015,
    type:"",
    style:"",
    title:"",
    titileCN:"",
    text:"The shadow is slanted in spring, the family help the sinners back",
    textCN:"",
    img:"",
    horizontal:false,
},
{
    id:10016,
    type:"",
    style:"",
    title:"",
    titileCN:"",
    text:"Clear and bright  moon cast its light on the  pine woods,while creeks  flow  above the stones.",
    textCN:"",
    img:"",
    horizontal:false,
}
         
         ]
//step1:build data model
//step2:design html
//step3:design a sigle card
//step4:iterate/loop the data and make one card for each object
//step4a:create the pop
//step5:polish