var painting = [
    {
        id:20001,
        type:"",
        style:"",
        title:"",
        titleCN:"",
        text:"The whale's wings have been cut and itself has been thrown to the sea.",
        textCN:"",
        img:"https:picsum.photos/200/1500",
        horizontal:false,
    
},
    {
        id:20002,
        type:"",
        style:"",
        title:"",
        titleCN:"",
        text:"This dying pig is preapared for the coming festival.",
        textCN:"",
        img:"http:picsum.photos/600/300",
        horizaontal:false,
    
},
    {
        id:20003,
        type:"",
        style:"",
        title:"",
        titleCN:"",
        text:"country-side living style",
        textCN:"",
        img:"",
        horizontal:false,
},
    {
        id:20004,
        type:"",
        style:"",
        title:"",
        titileCN:"",
        text:"landscape drawing",
        textCN:"",
        img:"",
        horizontal:true,
},
    {
        id:20005,
        type:"",
        style:"",
        title:"",
        titleCN:"",
        text:"observational drawing",
        textCN:"",
        img:"",
        horizontal:false,
},
    {
        id:20006,
        type:"",
        style:"",
        title:"",
        titileCN:"",
        text:"self-portrait",
        textCN:"",
        img:"",
        horizontal:false,
},
    {
        id:20007,
        type:"",
        style:"",
        title:"",
        titileCN:"",
        text:"portrait practice",
        textCN:"",
        img:"",
        horizontal:true,
    },
    {
        id:20008,
        type:"",
        style:"",
        title:"",
        titleCN:"",
        text:"portrait practice",
        textCN:"",
        img:"",
        horizontal:false,
    },
    {
        id:20009,
        type:"",
        style:"",
        title:"",
        titileCN:"",
        text:"portrait practice",
        textCN:"",
        img:"",
        horizontal:false,
    },
    {
        id:20010,
        type:"",
        style:"",
        title:"",
        titileCN:"",
        text:"portrait practice",
        textCN:"",
        img:"",
        horizontal:true,
},
    {
        id:20011,
        type:"",
        style:"",
        title:"",
        titleCN:"",
        text:"portrait practice",
        textCN:"",
        img:"",
        horizontal:false,
},
    {
        id:20012,
        type:"",
        style:"",
        title:"",
        titileCN:"",
        text:"portrait practice",
        textCN:"",
        img:"",
        horizontal:false,
},
   
    
         
         ]